name: Build and push images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  prepare:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix
        id: set-matrix
        run: |
          images_json_obj="$(./generate-matrix.sh)"
          echo "matrix=${images_json_obj}" | tee -a $GITHUB_OUTPUT

  main:
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/emqx/${{ matrix.image[0] }}:${{ matrix.image[1] }}
          file: ${{ matrix.image[0] }}/Dockerfile
          context: ${{ matrix.image[0] }}
