name: Build and push images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  prepare:
    runs-on: ubuntu-26.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Generate matrix
        id: set-matrix
        run: |
          images_json_obj="$(./generate-matrix.sh)"
          echo "matrix=${images_json_obj}" | tee -a $GITHUB_OUTPUT

  main:
    needs: prepare
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Docker login
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: ${{ github.event_name == 'push' }}
          platforms: ${{ matrix.image[2] }}
          tags: ${{ matrix.image[3] }}
          file: ${{ matrix.image[0] }}/Dockerfile
          context: ${{ matrix.image[0] }}
          cache-from: type=registry,mode=max,ref=ghcr.io/emqx/${{ matrix.image[0] }}:build-cache
          cache-to: type=registry,mode=max,ref=ghcr.io/emqx/${{ matrix.image[0] }}:build-cache
