name: Build and push images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image:
          - 'package_cloud'
          - 'certgen'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/emqx/${{ matrix.image }}
          file: ${{ matrix.image }}/Dockerfile
          context: ${{ matrix.image }}
