name: Build and push images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Generate matrix
        id: set-matrix
        run: |
          images_json_obj="$(./generate-matrix.sh)"
          echo "matrix=${images_json_obj}" | tee -a $GITHUB_OUTPUT

  main:
    needs: prepare
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Docker login
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
        with:
          push: true
          platforms: ${{ matrix.image[2] }}
          tags: ghcr.io/emqx/${{ matrix.image[0] }}:${{ matrix.image[1] }}
          file: ${{ matrix.image[0] }}/Dockerfile
          context: ${{ matrix.image[0] }}
